const names = new Map([
    ["Ormus' Robes", "Robe d'Ormus"],
    ["The Gladiator's Bane" , "" ],
    ["Arkaine's Valor", "" ],
    ["Leviathan", "" ],
    ["Steel Carapace", "" ],
    ["Templar's Might", "" ],
    ["Tyrael's Might", "" ],
    ["Lenymo", "" ],
    ["Snakecord", "" ],
    ["Nightsmoke", "" ],
    ["Goldwrap", "" ],
    ["Bladebuckle", "" ],
    ["String of Ears", "" ],
    ["Razortail", "" ],
    ["Gloom's Trap", "" ],
    ["Snowclash", "" ],
    ["Thundergod's Vigor", "" ],
    ["Greyform", "" ],
    ["Blinkbat's Form", "" ],
    ["The Centurion", "" ],
    ["Twitchthroe", "" ],
    ["Darkglow", "" ],
    ["Hawkmail", "" ],
    ["Venom Ward", "" ],
    ["Sparking Mail", "" ],
    ["Iceblink", "" ],
    ["Heavenly Garb", "" ],
    ["Rockfleece", "" ],
    ["Boneflesh", "" ],
    ["Rattlecage", "" ],
    ["Goldskin", "" ],
    ["Silks of the Victor", "" ],
    ["The Spirit Shroud", "" ],
    ["Skin of the Vipermagi", "" ],
    ["Skin of the Flayed One", "" ],
    ["Iron Pelt", "" ],
    ["Crow Caw", "" ],
    ["Spirit Forge", "" ],
    ["Duriel's Shell", "" ],
    ["Shaftstop", "" ],
    ["Skullder's Ire", "" ],
    ["Que-Hegan's Wisdom", "" ],
    ["Toothrow", "" ],
    ["Guardian Angel", "" ],
    ["Atma's Wail", "" ],
    ["Black Hades", "" ],
    ["Corpsemourn", "" ],
    ["Sandstorm Trek", "" ],
    ["Marrowwalk", "" ],
    ["Shadow Dancer", "" ],
    ["Arachnid Mesh", "" ],
    ["Nosferatu's Coil", "" ],
    ["Verdungo's Hearty Cord", "" ],
    ["Dracul's Grasp", "" ],
    ["Soul Drainer", "" ],
    ["Steelrend", "" ],
    ["Venom Grip", "" ],
    ["Gravepalm", "" ],
    ["Ghoulhide", "" ],
    ["Lava Gout", "" ],
    ["Hellmouth", "" ],
    ["Infernostride", "" ],
    ["Waterwalk", "" ],
    ["Silkweave", "" ],
    ["War Traveler", "" ],
    ["Gore Rider", "" ],
    ["Hotspur", "" ],
    ["Gorefoot", "" ],
    ["Treads of Cthon", "" ],
    ["Goblin Toe", "" ],
    ["Tearhaunch", "" ],
    ["Harlequin Crest", "" ],
    ["Steel Shade", "" ],
    ["Veil of Steel", "" ],
    ["Nightwing's Veil", "" ],
    ["Andariel's Visage", "" ],
    ["Crowned of Ages", "" ],
    ["Giant Skull", "" ],
    ["The Hand of Broc", "" ],
    ["Bloodfist", "" ],
    ["Chance Guards", "" ],
    ["Magefist", "" ],
    ["Frostburn", "" ],
    ["Peasant Crowned", "" ],
    ["Rockstopper", "" ],
    ["Stealskull", "" ],
    ["Darksight Helm", "" ],
    ["Valkyrie Wing", "" ],
    ["Blackhorn's Face", "" ],
    ["Crowned of Thieves", "" ],
    ["Vampire Gaze", "" ],
    ["Biggin's Bonnet", "" ],
    ["Tarnhelm", "" ],
    ["Coif of Glory", "" ],
    ["Duskdeep", "" ],
    ["Howltusk", "" ],
    ["The Face of Horror", "" ],
    ["Undead Crowned", "" ],
    ["Wormskull", "" ],
    ["Pelta Lunata", "" ],
    ["Umbral Disk", "" ],
    ["Stormguild", "" ],
    ["Steelclash", "" ],
    ["Swordback Hold", "" ],
    ["Bverrit Keep", "" ],
    ["Wall of the Eyeless", "" ],
    ["The Ward", "" ],
    ["Blackoak Shield", "" ],
    ["Stormshield", "" ],
    ["Spike Thorn", "" ],
    ["Medusa's Gaze", "" ],
    ["Head Hunter's Glory", "" ],
    ["Spirit Ward", "" ],
    ["Shadow Killer", "" ],
    ["Bartuc's Cut-Throat", "" ],
    ["Jade Talon", "" ],
    ["Firelizard's Talons", "" ],
    ["Visceratuant", "" ],
    ["Moser's Blessed Circle", "" ],
    ["Stormchaser", "" ],
    ["Tiamat's Rebuke", "" ],
    ["Lance Guard", "" ],
    ["Gerke's Sanctuary", "" ],
    ["Lidless Wall", "" ],
    ["Radament's Sphere", "" ],
    ["Arreat's Face", "" ],
    ["Wolfhowl", "" ],
    ["Demonhorn's Edge", "" ],
    ["Halaberd's Reign", "" ],
    ["Stoneraven", "" ],
    ["Lycander's Flank", "" ],
    ["Lycander's Aim", "" ],
    ["Titan's Revenge", "" ],
    ["Thunderstroke", "" ],
    ["Blood Raven's Charge", "" ],
    ["Homunculus", "" ],
    ["Darkforce Spawn", "" ],
    ["Boneflame", "" ],
    ["Alma Negra", "" ],
    ["Herald Of Zakarum", "" ],
    ["Dragonscale", "" ],
    ["Jalal's Mane", "" ],
    ["Cerebus' Bite", "" ],
    ["Ravenlore", "" ],
    ["Spirit Keeper", "" ],
    ["Coldkill", "" ],
    ["Butcher's Pupil", "" ],
    ["Islestrike", "" ],
    ["Pompeii's Wrath", "" ],
    ["Guardian Naga", "" ],
    ["Warlord's Trust", "" ],
    ["Spellsteel", "" ],
    ["Stormrider", "" ],
    ["Boneslayer Blade", "" ],
    ["The Minotaur", "" ],
    ["Eaglehorn", "" ],
    ["Widowmaker", "" ],
    ["Windforce", "" ],
    ["Razor's Edge", "" ],
    ["Rune Master", "" ],
    ["Cranebeak", "" ],
    ["Death Cleaver", "" ],
    ["Ethereal Edge", "" ],
    ["Hellslayer", "" ],
    ["Messerschmidt's Reaver", "" ],
    ["Executioner's Justice", "" ],
    ["The Oculus", "" ],
    ["Eschuta's Temper", "" ],
    ["Death's Fathom", "" ],
    ["Skystrike", "" ],
    ["Riphook", "" ],
    ["Kuko Shakaku", "" ],
    ["Endlesshail", "" ],
    ["Witchwild String", "" ],
    ["Cliffkiller", "" ],
    ["Magewrath", "" ],
    ["Goldstrike Arch", "" ],
    ["The Gnasher", "" ],
    ["Deathspade", "" ],
    ["Bladebone", "" ],
    ["Skull Splitter", "" ],
    ["Rakescar", "" ],
    ["Axe of Fechmar", "" ],
    ["Goreshovel", "" ],
    ["The Chieftain", "" ],
    ["Brainhew", "" ],
    ["Humongous", "" ],
    ["Pluckeye", "" ],
    ["Witherstring", "" ],
    ["Raven Claw", "" ],
    ["Rogue's Bow", "" ],
    ["Stormstrike", "" ],
    ["Wizendraw", "" ],
    ["Hellclap", "" ],
    ["Blastbark", "" ],
    ["Hellrack", "" ],
    ["Gut Siphon", "" ],
    ["Langer Briser", "" ],
    ["Pus Spitter", "" ],
    ["Buriza-Do Kyanon", "" ],
    ["Demon Machine", "" ],
    ["Leadcrow", "" ],
    ["Ichorsting", "" ],
    ["Hellcast", "" ],
    ["Doomslinger", "" ],
    ["Wizardspike", "" ],
    ["Fleshripper", "" ],
    ["Ghostflame", "" ],
    ["Spineripper", "" ],
    ["Heart Carver", "" ],
    ["Blackbog's Sharp", "" ],
    ["Stormspike", "" ],
    ["Gull", "" ],
    ["The Diggler", "" ],
    ["The Jade Tan Do", "" ],
    ["Spectral Shard", "" ],
    ["Nord's Tenderizer", "" ],
    ["Demon Limb", "" ],
    ["Baranar's Star", "" ],
    ["Horizon's Tornado", "" ],
    ["Stormlash", "" ],
    ["Stone Crusher", "" ],
    ["Schaefer's Hammer", "" ],
    ["Windhammer", "" ],
    ["Earth Shifter", "" ],
    ["The Cranium Basher", "" ],
    ["Dark Clan Crusher", "" ],
    ["Fleshrender", "" ],
    ["Sureshrill Frost", "" ],
    ["Moonfall", "" ],
    ["Baezil's Vortex", "" ],
    ["Earthshaker", "" ],
    ["Bloodtree Stump", "" ],
    ["The Gavel Of Pain", "" ],
    ["Demon's Arch", "" ],
    ["Wraith Flight", "" ],
    ["Gargoyle's Bite", "" ],
    ["Felloak", "" ],
    ["Stoutnail", "" ],
    ["Crushflange", "" ],
    ["Bloodrise", "" ],
    ["The General's Tan Do Li Ga", "" ],
    ["Ironstone", "" ],
    ["Bonesnap", "" ],
    ["Steeldriver", "" ],
    ["Dimoak's Hew", "" ],
    ["Steelgoad", "" ],
    ["Soul Harvest", "" ],
    ["The Battlebranch", "" ],
    ["Woestave", "" ],
    ["The Grim Reaper", "" ],
    ["Bonehew", "" ],
    ["The Reaper's Toll", "" ],
    ["Tomb Reaver", "" ],
    ["Stormspire", "" ],
    ["Heaven's Light", "" ],
    ["The Redeemer", "" ],
    ["Astreon's Iron Ward", "" ],
    ["The Meat Scraper", "" ],
    ["Blackleach Blade", "" ],
    ["Athena's Wrath", "" ],
    ["Pierre Tombale Couant", "" ],
    ["Husoldal Evo", "" ],
    ["Grim's Burning Dead", "" ],
    ["Zakarum's Hand", "" ],
    ["The Fetid Sprinkler", "" ],
    ["Hand of Blessed Light", "" ],
    ["The Impaler", "" ],
    ["Kelpie Snare", "" ],
    ["Soulfeast Tine", "" ],
    ["Hone Sundan", "" ],
    ["Spire of Honor", "" ],
    ["Knell Striker", "" ],
    ["Rusthandle", "" ],
    ["Stormeye", "" ],
    ["The Dragon Chang", "" ],
    ["Razortine", "" ],
    ["Bloodthief", "" ],
    ["Lance of Yaggai", "" ],
    ["The Tannr Gorerod", "" ],
    ["Arioc's Needle", "" ],
    ["Viperfork", "" ],
    ["Steel Pillar", "" ],
    ["Razorswitch", "" ],
    ["Ribcracker", "" ],
    ["Chromatic Ire", "" ],
    ["Warpspear", "" ],
    ["Skull Collector", "" ],
    ["Ondal's Wisdom", "" ],
    ["Mang Song's Lesson", "" ],
    ["Bane Ash", "" ],
    ["Serpent Lord", "" ],
    ["Spire of Lazarus", "" ],
    ["The Salamander", "" ],
    ["The Iron Jang Bong", "" ],
    ["Bloodletter", "" ],
    ["Coldsteel Eye", "" ],
    ["Hexfire", "" ],
    ["Blade Of Ali Baba", "" ],
    ["Ginther's Rift", "" ],
    ["Headstriker", "" ],
    ["Plague Bearer", "" ],
    ["The Atlantean", "" ],
    ["Crainte Vomir", "" ],
    ["Bing Sz Wang", "" ],
    ["The Vile Husk", "" ],
    ["Cloudcrack", "" ],
    ["Todesfaelle Flamme", "" ],
    ["Swordguard", "" ],
    ["Djinn Slayer", "" ],
    ["Bloodmoon", "" ],
    ["Lightsabre", "" ],
    ["Azurewrath", "" ],
    ["Frostwind", "" ],
    ["Flamebellow", "" ],
    ["Doombringer", "" ],
    ["The Grandfather", "" ],
    ["Warshrike", "" ],
    ["Gimmershred", "" ],
    ["Lacerator", "" ],
    ["Rixot's Keen", "" ],
    ["Blood Crescent", "" ],
    ["Skewer of Krintiz", "" ],
    ["Gleamscythe", "" ],
    ["Griswold's Edge", "" ],
    ["Hellplague", "" ],
    ["Culwen's Point", "" ],
    ["Shadowfang", "" ],
    ["Soulflay", "" ],
    ["Kinemil's Awl", "" ],
    ["Blacktongue", "" ],
    ["Ripsaw", "" ],
    ["The Patriarch", "" ],
    ["Deathbit", "" ],
    ["The Scalper", "" ],
    ["Boneshade", "" ],
    ["Death's Web", "" ],
    ["Suicide Branch", "" ],
    ["Carin Shard", "" ],
    ["Arm of King Leoric", "" ],
    ["Blackhand Key", "" ],
    ["Torch of Iro", "" ],
    ["Maelstrom", "" ],
    ["Gravenspine", "" ],
    ["Ume's Lament", "" ],
    ["Annihilus", "" ],
    ["Gheed's Fortune", "" ],
    ["Hellfire Torch", "" ],
    ["Nokozan Relic", "" ],
    ["The Eye of Etlich", "" ],
    ["The Mahim-Oak Curio", "" ],
    ["Saracen's Chance", "" ],
    ["The Cat's Eye", "" ],
    ["Crescent Moon", "" ],
    ["Atma's Scarab", "" ],
    ["The Rising Sun", "" ],
    ["Highlord's Wrath", "" ],
    ["Mara's Kaleidoscope", "" ],
    ["Seraph's Hymn", "" ],
    ["Metalgrid", "" ],
    ["Kira's Guardian", "" ],
    ["Griffon's Eye", "" ],
    ["Fire Level Up", "" ],
    ["Cold Level Up", "" ],
    ["Light Level Up", "" ],
    ["Poison Level Up", "" ],
    ["Fire Die", "" ],
    ["Cold Die", "" ],
    ["Light Die", "" ],
    ["Poison Die", "" ],
    ["Nagelring", "" ],
    ["Manald Heal", "" ],
    ["Stone of Jordan", "" ],
    ["Dwarf Star", "" ],
    ["Raven Frost", "" ],
    ["Bul-Kathos' Wedding Band", "" ],
    ["Carrion Wind", "" ],
    ["Nature's Peace", "" ],
    ["Wisp Projector", "" ]
]);


exports.names = names
