module.exports = [
    "Angelic Raiment",
    "Arcanna's Tricks",
    "Arctic Gear",
    "Berserker's Arsenal",
    "Cathan's Traps",
    "Civerb's Vestments",
    "Cleglaw's Brace",
    "Death's Disguise",
    "Hsaru's Defense",
    "Infernal Tools",
    "Iratha's Finery",
    "Isenhart's Armory",
    "Milabrega's Regalia",
    "Sigon's Complete Steel",
    "Tancred's Battlegear",
    "Vidala's Rig",
    "Aldur's Watchtower",
    "Bul-Kathos' Children",
    "Cow King's Leathers",
    "Griswold's Legacy",
    "Heaven's Brethren",
    "Hwanin's Majesty",
    "Immortal King",
    "M'avina's Battle Hymn",
    "Naj's Ancient Vestige",
    "Natalya's Odium",
    "Orphan's Call",
    "Sander's Folly",
    "Sazabi's Grand Tribute",
    "Tal Rasha's Wrappings",
    "The Disciple",
    "Trang-Oul's Avatar"
]